Version 4
SymbolType BLOCK
SYMATTR SpiceModel LM334
PIN -112 -32 RIGHT 8
PINATTR PinName v+
PINATTR SpiceOrder 1
PIN -112 32 RIGHT 8
PINATTR PinName v-
PINATTR SpiceOrder 2
PIN -112 0 RIGHT 8
PINATTR PinName R
PINATTR SpiceOrder 3
